name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: ['16', '18', '20']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: |
          - args: [--frozen-lockfile]
    - run: pnpm run build
      env:
        CI: true
    - run: pnpm run test
      env:
        CI: true
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./test/coverage/lcov.info"
